---
title: "Cohen Maps Unsupevised"
author: "Desmond Gukwe"
date: "29/05/2019"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
library(caret)
library(dplyr)
library(ggplot2)
library(lattice)
library(gridExtra)
```


```{r cars}
library(kohonen)
winequality_red <- read_csv("Downloads/Wine-Quality--master/winequality_red.csv")
winequality_white<- read_csv("Downloads/Wine-Quality--master/winequality_white.csv")
data<-winequality_white
str(data)
```
```{r}
library(DataExplorer)
plot_missing(data)
```
```{r}
data$quality<-factor(data$quality)

plot_bar(data)

```
```{r}
plot_histogram(data)
```
```{r}
plot_histogram(X)

```

```{r}
pd <- sample(2,nrow(data),replace = TRUE , prob =c(0.7,0.3))
train <-data[pd==1,]
test<- data[pd==2,]
library(party)
table(train$quality)
tree_ <-ctree(quality~.,data=train,controls =ctree_control(mincriterion = 0.90,minsplit =200))
confusionMatrix(predict(tree_,test),test$quality ,positive = '1')
plot(tree_)
```

```{r}
df<-dplyr::select(data,-c(quality))

X<-base::scale(df)
set.seed(123)
g<-somgrid(xdim = 5,ydim = 5,topo = "rectangular")
map <-som(X,grid= g,alpha= c(0.005,0.01),radius =1)
plot(map,type='changes')

```
```{r}
plot(map)
```

```{r}
plot(map,type = 'codes',palette.name = rainbow,main = '4x4')
```

```{r}
plot(map,type = 'dist.neighbours')
```
```{r}
set.seed(123)
ind<-sample(2,nrow(data),replace = T,prob = c(.7,.3))
train<-data[ind==1,]
test<-data[ind==2,]
trainX<-scale(train[,-1])
```
```{r}
library(plotly)
set.seed(100)
d <- diamonds[sample(nrow(diamonds), 1000), ]
plot_ly(d, x = carat, y = price, text = paste("Clarity: ", clarity),
        mode = "markers", color = carat, size = carat)
```

